name: Build and Release Package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag to upload assets to (e.g., v1.0.1)"
        required: false
        default: ""

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Upload release assets (auto release)
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} dist/* --clobber

      - name: Upload release assets (manual trigger)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.release_tag != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.inputs.release_tag }} dist/* --clobber

      - name: Upload to latest release (manual trigger without tag)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.release_tag == ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_TAG=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
          echo "Uploading to latest release: $LATEST_TAG"
          gh release upload $LATEST_TAG dist/* --clobber

      - name: Publish to PyPI (if API token is available)
        if: github.event_name == 'release'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          if [ -n "$TWINE_PASSWORD" ]; then
            echo "Publishing to PyPI..."
            twine upload dist/*
          else
            echo "PYPI_API_TOKEN not set, skipping PyPI upload"
          fi
